// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
        case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
     apiKey: "AIzaSyCJvEiMcmvnwxKjLjHA9_WRQQn8tfOzCNg",
      authDomain: "attandence-app-3a817.firebaseapp.com",
      projectId: "attandence-app-3a817",
      storageBucket: "attandence-app-3a817.firebasestorage.app",
      messagingSenderId: "19185238714",
      appId: "1:19185238714:web:ab89b4e486eb47188d7883",
      measurementId: "G-NW0BM4FSDP"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxxtYihoLUPMQhh9o2a3pXUJGKbERY8l4',
    appId: '1:19185238714:android:1dba7195f5b307448d7883',
    messagingSenderId: '19185238714',
    projectId: 'attandence-app-3a817',
    storageBucket: 'attandence-app-3a817.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt7ewtC0wzGUKMaGDDmd_ohxtRtOAH8kg',
    appId: '1:19185238714:ios:70b8f68c23571ffe8d7883',
    messagingSenderId: '19185238714',
    projectId: 'attandence-app-3a817',
    storageBucket: 'attandence-app-3a817.firebasestorage.app',
    iosBundleId: 'com.example.CampusOne',
  );

}
